spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev?useSSL=false
    username: sfg_dev
    password: guru
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              crate-target: guru_database_create.sql